import type { DatabaseMenu } from "../types/database.types";

export const databaseMenus = [
  {
    id: "overview",
    name: "Overview",
    description: "Ringkasan import, validasi, dan publish data.",
    badge: "Prioritas awal",
    badgeTone: "green",
    href: "/database/overview",
    isActive: true,
  },
  {
    id: "import-center",
    name: "Import Center",
    description: "Upload CSV/XLSX dan mulai proses import data.",
    badge: "Fase 1 aktif",
    badgeTone: "green",
    href: "/database/import-center",
    isActive: true,
  },
  {
    id: "source-systems",
    name: "Source Systems",
    description: "Kelola sumber data dan koneksi import.",
    badge: "Active",
    badgeTone: "active",
    href: "/database/source-systems",
    isActive: true,
  },
  {
    id: "validation-issues",
    name: "Validation Issues",
    description: "Review error, field kosong, dan masalah validasi.",
    badge: "Prioritas awal",
    badgeTone: "green",
    href: "/database/validation-issues",
    isActive: true,
  },
  {
    id: "duplicate-review",
    name: "Duplicate Review",
    description: "Cek dan review kemungkinan data duplikat.",
    badge: "Active",
    badgeTone: "active",
    href: "/database/duplicate-review",
    isActive: true,
  },
  {
    id: "mapping-center",
    name: "Mapping Center",
    description: "Mapping produk, customer, platform, dan payment.",
    badge: "Fase 1 aktif",
    badgeTone: "green",
    href: "/database/mapping-center",
    isActive: true,
  },
  {
    id: "publish-center",
    name: "Publish Center",
    description: "Publish data valid ke database utama ERP.",
    badge: "Active",
    badgeTone: "active",
    href: "/database/publish-center",
    isActive: true,
  },
] satisfies DatabaseMenu[];
