"use client";
import { useEffect, useState } from "react";
import { DummyBanner } from "@/features/marketing/components/DummyBanner";
import { MarketingBackButton } from "@/features/marketing/components/MarketingBackButton";
import { getCrmAds, getCrmDataTerkini } from "./lib/crmService";
import { formatRatio, formatRingkas } from "./lib/crmUtils";
import { CrmBars, CrmCard, CrmDonut, CrmFilterBar, CrmKpis, CrmLine, CrmPageHeader, CrmPageShell } from "./components/CrmUi";
import type { CrmAdsData, CrmAdsRow } from "./types/crmTypes";

const tone: Record<CrmAdsRow["status"], string> = { Bagus: "bg-emerald-50 text-emerald-700", Cek: "bg-amber-50 text-amber-700", Evaluasi: "bg-red-50 text-red-700", Pause: "bg-slate-100 text-slate-600" };
export function CrmAdsPage() { const [data, setData] = useState<CrmAdsData | null>(null), [values, setValues] = useState<Record<string, string>>({}); const load = () => { getCrmAds(values).then(setData); }; useEffect(() => { getCrmAds({}).then(setData); }, []); return <CrmPageShell><DummyBanner /><CrmPageHeader title="Data Iklan CRM" subtitle="Pantau spending, leads, closing, sales CRM, cost per closing, dan performa campaign CRM." update={getCrmDataTerkini()} />{data && <><CrmFilterBar options={data.filters} values={values} onChange={(key, value) => setValues((current) => ({ ...current, [key]: value }))} onApply={load} /><CrmKpis items={data.kpi} /><div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><CrmCard title="Spending vs Sales CRM" className="xl:col-span-2"><CrmLine data={data.trend} secondaryLabel="Sales CRM" /></CrmCard><CrmCard title="Closing per Campaign"><CrmBars data={data.campaignClosing} /></CrmCard><CrmCard title="Cost per Closing per ADV"><CrmBars data={data.costByAdv} money /></CrmCard><CrmCard title="Distribusi Spending CRM"><CrmDonut data={data.spendingDistribution} /></CrmCard></div><CrmCard title="Detail Data Iklan CRM"><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-xs font-bold uppercase tracking-wide text-slate-400">{["Tanggal", "Platform", "ADV", "Campaign", "Spending", "Leads", "Closing", "Sales CRM", "Cost / Closing", "ROAS", "Status"].map((head) => <th key={head} className="px-2 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-50">{data.rows.map((row) => <tr key={row.id}><td className="px-2 py-3">{row.tanggal}</td><td className="px-2 py-3">{row.platform}</td><td className="px-2 py-3">{row.adv}</td><td className="px-2 py-3 font-bold text-slate-900">{row.campaign}</td><td className="px-2 py-3 text-right">{formatRingkas(row.spending)}</td><td className="px-2 py-3 text-right">{row.leads}</td><td className="px-2 py-3 text-right">{row.closing}</td><td className="px-2 py-3 text-right">{formatRingkas(row.sales)}</td><td className="px-2 py-3 text-right">{row.closing ? formatRingkas(row.costPerClosing) : "-"}</td><td className="px-2 py-3 text-right">{formatRatio(row.sales, row.spending)}</td><td className="px-2 py-3"><span className={`rounded-md px-2 py-1 text-xs font-bold ${tone[row.status]}`}>{row.status}</span></td></tr>)}</tbody></table></div></CrmCard></>}<div><MarketingBackButton href="/marketing/crm" label="Kembali ke CRM" /></div></CrmPageShell>; }
