"use client";
import { useEffect, useState } from "react";
import { DummyBanner } from "@/features/marketing/components/DummyBanner";
import { MarketingBackButton } from "@/features/marketing/components/MarketingBackButton";
import { getCrmDataReview, getCrmDataTerkini } from "./lib/crmService";
import { CrmBars, CrmCard, CrmDetailDrawer, CrmDonut, CrmFilterBar, CrmKpis, CrmLine, CrmPageHeader, CrmPageShell } from "./components/CrmUi";
import type { CrmReviewData } from "./types/crmTypes";

export function CrmDataReviewPage() { const [data, setData] = useState<CrmReviewData | null>(null), [values, setValues] = useState<Record<string, string>>({}), [customerId, setCustomerId] = useState<string | null>(null); const load = () => { getCrmDataReview(values).then(setData); }; useEffect(() => { getCrmDataReview({}).then(setData); }, []); return <CrmPageShell><DummyBanner /><CrmPageHeader title="Data Review CRM" subtitle="Lihat data CRM yang bermasalah dan perlu diperbaiki agar follow-up dan laporan tetap akurat." update={getCrmDataTerkini()} />{data && <><CrmFilterBar options={data.filters} values={values} onChange={(key, value) => setValues((current) => ({ ...current, [key]: value }))} onApply={load} /><CrmKpis items={data.kpi} /><div className="grid grid-cols-1 gap-4 xl:grid-cols-3"><CrmCard title="Jenis Issue"><CrmDonut data={data.issueDonut} /></CrmCard><CrmCard title="Issue per Sumber Data"><CrmBars data={data.issueBySource} /></CrmCard><CrmCard title="Tren Issue Harian"><CrmLine data={data.issueTrend} /></CrmCard></div><CrmCard title="Data Review CRM"><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-xs font-bold uppercase tracking-wide text-slate-400">{["Tipe Data", "Customer", "No WA", "Masalah", "Dampak", "Prioritas", "Rekomendasi Aksi", "Status", "Aksi"].map((head) => <th key={head} className="px-2 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-50">{data.rows.map((row) => <tr key={row.id} className="cursor-pointer hover:bg-slate-50" onClick={() => setCustomerId(row.customerId)}><td className="px-2 py-3">{row.tipeData}</td><td className="px-2 py-3 font-bold text-slate-900">{row.customer}</td><td className="px-2 py-3 text-blue-600">{row.noWa}</td><td className="px-2 py-3">{row.masalah}</td><td className="px-2 py-3 text-slate-500">{row.dampak}</td><td className="px-2 py-3"><b className={row.prioritas === "Tinggi" ? "text-red-600" : row.prioritas === "Sedang" ? "text-amber-600" : "text-emerald-600"}>{row.prioritas}</b></td><td className="px-2 py-3">{row.rekomendasi}</td><td className="px-2 py-3">{row.status}</td><td className="px-2 py-3"><button className="rounded-lg border border-slate-200 px-2 py-1 text-xs font-bold text-brand-red">Lihat</button></td></tr>)}</tbody></table></div></CrmCard></>}<div><MarketingBackButton href="/marketing/crm" label="Kembali ke CRM" /></div><CrmDetailDrawer customerId={customerId} onClose={() => setCustomerId(null)} /></CrmPageShell>; }
