"use client";
import { useEffect, useState } from "react";
import { DummyBanner } from "@/features/marketing/components/DummyBanner";
import { MarketingBackButton } from "@/features/marketing/components/MarketingBackButton";
import { getCrmDataTerkini, getCrmOrders } from "./lib/crmService";
import { CrmCard, CrmCustomerTable, CrmDetailDrawer, CrmDonut, CrmFilterBar, CrmKpis, CrmLine, CrmPageHeader, CrmPageShell, CrmBars } from "./components/CrmUi";
import type { CrmOrdersData } from "./types/crmTypes";

export function CrmOrdersPage() { const [data, setData] = useState<CrmOrdersData | null>(null), [values, setValues] = useState<Record<string, string>>({}), [customerId, setCustomerId] = useState<string | null>(null); const load = () => { getCrmOrders(values).then(setData); }; useEffect(() => { load(); }, []); return <CrmPageShell><DummyBanner /><CrmPageHeader title="Data Pesanan CRM" subtitle="Pantau closingan customer, produk, CS/CRM, status grup, dan follow-up secara real-time." update={getCrmDataTerkini()} />{data && <><CrmFilterBar options={data.filters} values={values} onChange={(key, value) => setValues((current) => ({ ...current, [key]: value }))} onApply={load} /><CrmKpis items={data.kpi} /><div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><CrmCard title="Tren Closing Harian" className="xl:col-span-2"><CrmLine data={data.trend} secondaryLabel="Jumlah Closing" /></CrmCard><CrmCard title="Customer Baru vs Repeat"><CrmDonut data={data.customerSplit} /></CrmCard><CrmCard title="Closing per CS / CRM"><CrmBars data={data.closingByCs} /></CrmCard><CrmCard title="Produk Paling Banyak Closing"><CrmBars data={data.productClosing} /></CrmCard></div><CrmCard title="Data Pesanan CRM"><CrmCustomerTable rows={data.rows} onDetail={setCustomerId} /></CrmCard></>}<div><MarketingBackButton href="/marketing/crm" label="Kembali ke CRM" /></div><CrmDetailDrawer customerId={customerId} onClose={() => setCustomerId(null)} /></CrmPageShell>; }
