"use client";

import type { CrmFrequencyRow, CrmRetentionRow } from "../types/crmTypes";
import { formatRingkas, formatPersen, heatTone } from "../lib/crmUtils";

export function CrmRetentionMatrix({ rows, mode, onModeChange, onSelect }: { rows: CrmRetentionRow[]; mode: "users" | "revenue"; onModeChange: (mode: "users" | "revenue") => void; onSelect: (cohort: string) => void }) {
  const averages = Array.from({ length: 13 }, (_, month) => {
    const cells = rows.map((row) => row.months[month]).filter((cell): cell is NonNullable<typeof cell> => !!cell);
    return cells.length ? cells.reduce((sum, cell) => sum + cell.percent, 0) / cells.length : 0;
  });
  return <section className="rounded-xl border border-slate-300 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><p className="text-sm font-extrabold text-slate-800">Retention per Cohort</p><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><span>Show:</span><div className="inline-flex gap-1"><button onClick={() => onModeChange("users")} className={`rounded-lg border px-3 py-1.5 ${mode === "users" ? "border-blue-600 bg-blue-50 text-blue-600" : "border-slate-200 bg-white"}`}>Users</button><button onClick={() => onModeChange("revenue")} className={`rounded-lg border px-3 py-1.5 ${mode === "revenue" ? "border-blue-600 bg-blue-50 text-blue-600" : "border-slate-200 bg-white"}`}>Revenue</button></div></div></div><div className="max-h-[700px] overflow-auto"><table className="min-w-[1880px] border-separate border-spacing-0 text-center text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] font-extrabold uppercase text-slate-500"><tr>{["Cohort", "Total Sales", "New Cust (Rp)", "Retensi (Rp)", "Avg Retensi", "Rasio Retensi"].map((label) => <th key={label} className="border-b border-r border-slate-200 px-4 py-3 whitespace-nowrap">{label}</th>)}{Array.from({ length: 13 }, (_, month) => <th key={month} className="min-w-22 border-b border-r border-slate-200 px-3 py-3">Month {month}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.cohort}><td className="sticky left-0 z-[1] border-b border-r border-slate-200 bg-white px-4 py-3 text-left text-sm font-black text-slate-800">{row.cohort}</td><Metric value={formatRingkas(row.totalSales)} /><Metric value={formatRingkas(row.newCustomer)} /><Metric value={formatRingkas(row.retainedSales)} green /><Metric value={formatRingkas(row.avgRetention)} /><Metric value={formatPersen(row.retentionRatio)} />{row.months.map((cell, month) => <td key={month} className="border-b border-r border-slate-200 p-0">{cell ? <button onClick={() => onSelect(row.cohort)} className={`flex min-h-[58px] w-full flex-col items-center justify-center transition hover:ring-2 hover:ring-blue-500 ${heatTone(cell.percent)}`}><b className="text-sm">{mode === "users" ? cell.value : formatRingkas(Math.round(row.retainedSales * cell.percent / 100))}</b><span className="mt-0.5 text-[10px] opacity-75">{formatPersen(cell.percent)}</span></button> : <span className="flex min-h-[58px] items-center justify-center text-slate-300">–</span>}</td>)}</tr>)}</tbody><tfoot className="sticky bottom-0 bg-[#fff5f5] text-brand-red"><tr><td colSpan={6} className="border-t-2 border-brand-red px-4 py-3 text-right font-black">Rata-rata Retensi Global:</td>{averages.map((average, month) => <td key={month} className="border-t-2 border-brand-red px-3 py-3 font-black">{average ? formatPersen(average) : "–"}</td>)}</tr></tfoot></table></div></section>;
}

export function CrmFrequencyMatrix({ rows, onSelect }: { rows: CrmFrequencyRow[]; onSelect: (cohort: string) => void }) {
  return <section className="rounded-xl border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-200 px-4 py-3"><p className="text-sm font-extrabold text-slate-800">Frequency Order per Cohort</p></div><div className="max-h-[700px] overflow-auto"><table className="min-w-[2120px] border-separate border-spacing-0 text-center text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] font-extrabold uppercase text-slate-500"><tr><th className="border-b border-r border-slate-200 px-4 py-3">Cohort</th>{Array.from({ length: 19 }, (_, order) => <th key={order} className="min-w-23 border-b border-r border-slate-200 px-3 py-3">{order === 18 ? "19X+" : `${order + 1}X ORDER`}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.cohort}><td className="sticky left-0 z-[1] border-b border-r border-slate-200 bg-white px-4 py-3 text-left text-sm font-black text-slate-800">{row.cohort}</td>{row.orders.map((cell, order) => <td key={order} className="border-b border-r border-slate-200 p-0">{cell ? <button onClick={() => onSelect(row.cohort)} className={`flex min-h-[54px] w-full flex-col items-center justify-center transition hover:ring-2 hover:ring-blue-500 ${heatTone(cell.percent)}`}><b className="text-sm">{cell.value}</b><span className="mt-0.5 text-[10px] opacity-75">{formatPersen(cell.percent)}</span></button> : <span className="flex min-h-[54px] items-center justify-center text-slate-300">–</span>}</td>)}</tr>)}</tbody></table></div></section>;
}
function Metric({ value, green = false }: { value: string; green?: boolean }) { return <td className={`border-b border-r border-slate-200 px-4 py-3 font-bold ${green ? "text-emerald-600" : "text-slate-800"}`}>{value}</td>; }
