"use client";

import { useEffect, useState } from "react";
import { MarketingBackButton } from "@/features/marketing/components/MarketingBackButton";
import { AdsRoasHeader } from "./components/AdsRoasHeader";
import { AdsRoasFilterBar, type AdsRoasSelectFilter } from "./components/AdsRoasFilterBar";
import { AdsRoasTabs, type AdsRoasTabKey } from "./components/AdsRoasTabs";
import { AdsRoasKpiCard } from "./components/AdsRoasKpiCard";
import { AdsRoasChartCard } from "./components/AdsRoasChartCard";
import { AdsRoasTableCard, type AdsRoasTableColumn } from "./components/AdsRoasTableCard";
import { AdsRoasStatusBadge } from "./components/AdsRoasStatusBadge";
import { AdsRoasErrorState, AdsRoasKpiSkeleton, AdsRoasSectionSkeleton } from "./components/AdsRoasStates";
import { HorizontalValueBars, PlatformRoasBarChart, RoasDonutChart, SpendingSalesComparisonChart, SpendingSalesTrendChart, VerticalValueBarChart } from "./components/charts/AdsRoasCharts";
import { getAdsRoasByPlatform, getAdsRoasDataReview, getAdsRoasOverview, getAdvPerformance, getCampaignPerformance, getStorePerformance } from "./lib/marketingAdsRoasService";
import { formatNumber, formatPersen, formatRupiah, formatRupiahRingkas, roasOrDash } from "./lib/format";
import { filterOptionsMock } from "./data/temporaryAdsRoasMockData";
import type { AdsRoasSummary, AdvPerformanceData, AdvRow, CampaignPerformanceData, CampaignRow, DataReviewData, DataReviewItem, Platform, StorePerformanceData, StoreRow } from "./types/marketingAdsRoasTypes";

const PLATFORM_TAB: Partial<Record<AdsRoasTabKey, Platform>> = { tiktok: "TikTok", shopee: "Shopee", meta: "Meta Ads" };
const PRIORITY_TONE: Record<DataReviewItem["prioritas"], "red" | "amber" | "green"> = { Tinggi: "red", Sedang: "amber", Rendah: "green" };

export function AdsRoasPage() {
  const [tab, setTab] = useState<AdsRoasTabKey>("overview");
  const [periode, setPeriode] = useState("7hari");
  const [platform, setPlatform] = useState("Semua");
  const [adv, setAdv] = useState("Semua");
  const [toko, setToko] = useState("Semua");
  const [campaign, setCampaign] = useState("Semua");
  const [produk, setProduk] = useState("Semua");
  const [summary, setSummary] = useState<AdsRoasSummary | null>(null);
  const [advData, setAdvData] = useState<AdvPerformanceData | null>(null);
  const [campaignData, setCampaignData] = useState<CampaignPerformanceData | null>(null);
  const [storeData, setStoreData] = useState<StorePerformanceData | null>(null);
  const [reviewData, setReviewData] = useState<DataReviewData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const filters = { periode, platform, adv, toko, campaign, produk };

  const load = () => {
    setLoading(true); setError(false);
    const platformKey = PLATFORM_TAB[tab];
    const request = platformKey ? getAdsRoasByPlatform(platformKey, filters) : tab === "adv" ? getAdvPerformance(filters) : tab === "campaign" ? getCampaignPerformance(filters) : tab === "toko" ? getStorePerformance(filters) : tab === "review" ? getAdsRoasDataReview(filters) : getAdsRoasOverview(filters);
    request.then((res) => { if (tab === "adv") setAdvData(res as AdvPerformanceData); else if (tab === "campaign") setCampaignData(res as CampaignPerformanceData); else if (tab === "toko") setStoreData(res as StorePerformanceData); else if (tab === "review") setReviewData(res as DataReviewData); else setSummary(res as AdsRoasSummary); }).catch(() => setError(true)).finally(() => setLoading(false));
  };
  useEffect(load, [tab]); // eslint-disable-line react-hooks/exhaustive-deps
  const currentFilters = summary?.filters ?? advData?.filters ?? campaignData?.filters ?? storeData?.filters ?? reviewData?.filters ?? filterOptionsMock;
  const updateTerakhir = summary?.updateTerakhir ?? "";
  const selects: AdsRoasSelectFilter[] = [
    { key: "periode", label: "Periode", value: periode, icon: "calendar", options: currentFilters.periode }, { key: "platform", label: "Platform", value: platform, icon: "platform", options: currentFilters.platform },
    { key: "adv", label: "ADV", value: adv, icon: "adv", options: currentFilters.adv }, { key: "toko", label: "Toko", value: toko, icon: "toko", options: currentFilters.toko },
    { key: "campaign", label: "Campaign", value: campaign, icon: "campaign", options: currentFilters.campaign }, { key: "produk", label: "Produk", value: produk, icon: "produk", options: currentFilters.produk },
  ];
  const onSelectChange = (key: string, value: string) => { if (key === "periode") setPeriode(value); if (key === "platform") setPlatform(value); if (key === "adv") setAdv(value); if (key === "toko") setToko(value); if (key === "campaign") setCampaign(value); if (key === "produk") setProduk(value); };
  const isSummaryTab = tab === "overview" || !!PLATFORM_TAB[tab];
  const activeKpi = isSummaryTab ? summary?.kpi : tab === "adv" ? advData?.kpi : tab === "campaign" ? campaignData?.kpi : tab === "toko" ? storeData?.kpi : reviewData?.kpi;

  return <div className="min-h-screen overflow-x-hidden bg-[#eef2f6]/90 text-brand-deep"><main className="mx-auto flex w-full max-w-[1680px] flex-col gap-5 px-5 py-6 sm:px-7 lg:px-10">
    <AdsRoasHeader updateTerakhir={updateTerakhir} onRefresh={load} />
    <AdsRoasFilterBar selects={selects} onSelectChange={onSelectChange} onApply={load} />
    <AdsRoasTabs active={tab} onChange={setTab} />
    {error && <AdsRoasErrorState />}
    {loading && !activeKpi && <AdsRoasKpiSkeleton />}
    {activeKpi && <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-7">{activeKpi.map((item) => <AdsRoasKpiCard key={item.label} item={item} />)}</div>}
    {isSummaryTab && (loading && !summary ? <AdsRoasSectionSkeleton /> : summary && <SummaryTabContent data={summary} />)}
    {tab === "adv" && (loading && !advData ? <AdsRoasSectionSkeleton /> : advData && <AdvTabContent data={advData} />)}
    {tab === "campaign" && (loading && !campaignData ? <AdsRoasSectionSkeleton /> : campaignData && <CampaignTabContent data={campaignData} />)}
    {tab === "toko" && (loading && !storeData ? <AdsRoasSectionSkeleton /> : storeData && <StoreTabContent data={storeData} />)}
    {tab === "review" && (loading && !reviewData ? <AdsRoasSectionSkeleton /> : reviewData && <ReviewTabContent data={reviewData} />)}
    <div className="flex"><MarketingBackButton /></div>
  </main><footer className="pb-7 pt-3 text-center text-xs font-medium text-slate-500 sm:text-sm">© 2026 Probetes ERP. All rights reserved.</footer></div>;
}

function SummaryTabContent({ data }: { data: AdsRoasSummary }) {
  const advColumns: AdsRoasTableColumn<AdvRow>[] = [{ key: "rank", header: "#", render: (r) => r.rank }, { key: "adv", header: "ADV", render: (r) => <span className="font-extrabold text-slate-900">{r.adv}</span> }, { key: "spending", header: "Spending", align: "right", render: (r) => formatRupiahRingkas(r.spending) }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "roas", header: "ROAS", align: "right", render: (r) => roasOrDash(r.roas, r.spending) }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }];
  const campaignColumns: AdsRoasTableColumn<CampaignRow>[] = [{ key: "campaign", header: "Campaign", render: (r) => <span className="font-extrabold text-slate-900">{r.campaign}</span> }, { key: "platform", header: "Platform", render: (r) => r.platform }, { key: "spending", header: "Spending", align: "right", render: (r) => formatRupiahRingkas(r.spending) }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "roas", header: "ROAS", align: "right", render: (r) => roasOrDash(r.roas, r.spending) }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }];
  const storeColumns: AdsRoasTableColumn<StoreRow>[] = [{ key: "toko", header: "Toko", render: (r) => <span className="font-extrabold text-slate-900">{r.toko}</span> }, { key: "platform", header: "Platform", render: (r) => r.platform }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "order", header: "Order", align: "right", render: (r) => formatNumber(r.order) }, { key: "roas", header: "ROAS", align: "right", render: (r) => `${r.roas.toFixed(2)}x` }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }];
  const reviewColumns: AdsRoasTableColumn<DataReviewItem>[] = [{ key: "tipe", header: "Tipe Data", render: (r) => r.tipeData }, { key: "jumlah", header: "Jumlah", align: "right", render: (r) => r.jumlah }, { key: "masalah", header: "Masalah", render: (r) => r.masalah }];
  return <><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1.3fr_0.85fr_0.85fr_0.85fr]"><AdsRoasChartCard title="Tren Spending Ads vs Sales" action={<PeriodDropdown />}><SpendingSalesTrendChart labels={data.trend.map((t) => t.label)} spending={data.trend.map((t) => t.spending)} sales={data.trend.map((t) => t.sales)} formatValue={formatRupiahRingkas} /></AdsRoasChartCard><AdsRoasChartCard title="ROAS per Platform"><PlatformRoasBarChart data={data.roasPerPlatform} /></AdsRoasChartCard><AdsRoasChartCard title="Distribusi Spending Ads"><RoasDonutChart data={data.spendingDistribution} formatValue={formatRupiahRingkas} /></AdsRoasChartCard><AdsRoasChartCard title="Sales per Platform"><RoasDonutChart data={data.salesPerPlatformDonut} formatValue={formatRupiahRingkas} /></AdsRoasChartCard></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_1fr_1fr_1fr_1fr]"><AdsRoasChartCard title="Perbandingan Spending dan Sales per Platform" className="xl:col-span-2"><SpendingSalesComparisonChart data={data.comparisonPerPlatform} formatValue={formatRupiahRingkas} /></AdsRoasChartCard><AdsRoasTableCard title="Top ADV by ROAS" columns={advColumns} rows={data.topAdv} rowKey={(r) => r.adv} /><AdsRoasTableCard title="Top Campaign by ROAS" columns={campaignColumns} rows={data.topCampaign} rowKey={(r) => r.campaign} /><AdsRoasTableCard title="Top Toko by Sales" columns={storeColumns} rows={data.topStore} rowKey={(r) => r.toko} /></div><div className="grid grid-cols-1 xl:grid-cols-4"><AdsRoasTableCard title="Data Perlu Review" columns={reviewColumns} rows={data.dataReview} rowKey={(r) => `${r.tipeData}-${r.masalah}`} className="xl:col-span-1" /></div></>;
}
function PeriodDropdown() { return <select className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-bold text-slate-600 outline-none" defaultValue="harian"><option value="harian">Harian</option><option value="mingguan">Mingguan</option></select>; }
function AdvTabContent({ data }: { data: AdvPerformanceData }) { const columns: AdsRoasTableColumn<AdvRow>[] = [{ key: "adv", header: "ADV", render: (r) => <span className="font-extrabold text-slate-900">{r.adv}</span> }, { key: "platform", header: "Platform", render: (r) => r.platform }, { key: "spending", header: "Spending", align: "right", render: (r) => formatRupiahRingkas(r.spending) }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "order", header: "Order", align: "right", render: (r) => formatNumber(r.order) }, { key: "leads", header: "Leads", align: "right", render: (r) => formatNumber(r.leads) }, { key: "roas", header: "ROAS", align: "right", render: (r) => roasOrDash(r.roas, r.spending) }, { key: "cpo", header: "Cost per Order", align: "right", render: (r) => r.order > 0 ? formatRupiah(r.costPerOrder) : "-" }, { key: "closing", header: "Closing Rate", align: "right", render: (r) => r.leads > 0 ? formatPersen(r.closingRate, 1) : "-" }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }]; return <><AdsRoasChartCard title="ADV Terbaik"><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-bold text-emerald-700">ADV dengan ROAS tertinggi</p><p className="mt-1 text-2xl font-black text-emerald-800">{data.bestAdv.name}</p><p className="text-sm font-bold text-emerald-700">{data.bestAdv.roas > 0 ? `${data.bestAdv.roas.toFixed(2)}x` : "-"}</p></div></AdsRoasChartCard><div className="grid grid-cols-1 gap-4 xl:grid-cols-3"><AdsRoasChartCard title="ROAS per ADV"><VerticalValueBarChart data={data.roasPerAdv} formatValue={(v) => `${v.toFixed(2)}x`} /></AdsRoasChartCard><AdsRoasChartCard title="Spending per ADV"><VerticalValueBarChart data={data.spendingPerAdv} formatValue={formatRupiahRingkas} color="#2563EB" /></AdsRoasChartCard><AdsRoasChartCard title="Sales per ADV"><VerticalValueBarChart data={data.salesPerAdv} formatValue={formatRupiahRingkas} color="#7C3AED" /></AdsRoasChartCard></div><AdsRoasChartCard title="Detail ADV"><TableWithoutSeeAll columns={columns} rows={data.table} rowKey={(r) => r.adv} /></AdsRoasChartCard></>; }
function CampaignTabContent({ data }: { data: CampaignPerformanceData }) { const columns: AdsRoasTableColumn<CampaignRow>[] = [{ key: "campaign", header: "Campaign", render: (r) => <span className="font-extrabold text-slate-900">{r.campaign}</span> }, { key: "platform", header: "Platform", render: (r) => r.platform }, { key: "adv", header: "ADV", render: (r) => r.adv }, { key: "spending", header: "Spending", align: "right", render: (r) => formatRupiahRingkas(r.spending) }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "order", header: "Order", align: "right", render: (r) => formatNumber(r.order) }, { key: "leads", header: "Leads", align: "right", render: (r) => formatNumber(r.leads) }, { key: "roas", header: "ROAS", align: "right", render: (r) => roasOrDash(r.roas, r.spending) }, { key: "cpo", header: "Cost per Order", align: "right", render: (r) => r.order > 0 ? formatRupiah(r.costPerOrder) : "-" }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }]; return <><div className="grid grid-cols-1 gap-4 xl:grid-cols-3"><AdsRoasChartCard title="Top 10 Campaign by ROAS"><VerticalValueBarChart data={data.topByRoas.slice(0, 10)} formatValue={(v) => `${v.toFixed(2)}x`} /></AdsRoasChartCard><AdsRoasChartCard title="Top 10 Campaign by Sales"><VerticalValueBarChart data={data.topBySales.slice(0, 10)} formatValue={formatRupiahRingkas} color="#2563EB" /></AdsRoasChartCard><AdsRoasChartCard title="Campaign dengan ROAS Rendah"><TableWithoutSeeAll columns={[{ key: "campaign", header: "Campaign", render: (r) => r.campaign }, { key: "roas", header: "ROAS", align: "right", render: (r) => roasOrDash(r.roas, r.spending) }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }]} rows={data.lowRoas} rowKey={(r) => r.campaign} /></AdsRoasChartCard></div><AdsRoasChartCard title="Detail Campaign"><TableWithoutSeeAll columns={columns} rows={data.table} rowKey={(r) => r.campaign} /></AdsRoasChartCard></>; }
function StoreTabContent({ data }: { data: StorePerformanceData }) { const columns: AdsRoasTableColumn<StoreRow>[] = [{ key: "toko", header: "Toko", render: (r) => <span className="font-extrabold text-slate-900">{r.toko}</span> }, { key: "platform", header: "Platform", render: (r) => r.platform }, { key: "sales", header: "Sales", align: "right", render: (r) => formatRupiahRingkas(r.sales) }, { key: "order", header: "Order", align: "right", render: (r) => formatNumber(r.order) }, { key: "produk", header: "Produk Terlaris", render: (r) => <span className="text-slate-500">{r.produkTerlaris}</span> }, { key: "roas", header: "ROAS", align: "right", render: (r) => `${r.roas.toFixed(2)}x` }, { key: "status", header: "Status", render: (r) => <AdsRoasStatusBadge label={r.status} /> }]; return <><div className="grid grid-cols-1 gap-4 xl:grid-cols-3"><AdsRoasChartCard title="Sales per Toko"><VerticalValueBarChart data={data.salesPerStore} formatValue={formatRupiahRingkas} /></AdsRoasChartCard><AdsRoasChartCard title="Order per Toko"><VerticalValueBarChart data={data.orderPerStore} formatValue={formatNumber} color="#2563EB" /></AdsRoasChartCard><AdsRoasChartCard title="Kontribusi Sales Toko"><RoasDonutChart data={data.salesContributionDonut} formatValue={formatRupiahRingkas} /></AdsRoasChartCard></div><AdsRoasChartCard title="Detail Toko"><TableWithoutSeeAll columns={columns} rows={data.table} rowKey={(r) => r.toko} /></AdsRoasChartCard></>; }
function ReviewTabContent({ data }: { data: DataReviewData }) { const columns: AdsRoasTableColumn<DataReviewItem>[] = [{ key: "tipe", header: "Tipe Data", render: (r) => r.tipeData }, { key: "platform", header: "Platform", render: (r) => r.platform ?? "-" }, { key: "masalah", header: "Masalah", render: (r) => <span className="font-extrabold text-slate-900">{r.masalah}</span> }, { key: "dampak", header: "Dampak ke Laporan", render: (r) => <span className="text-slate-500">{r.dampak}</span> }, { key: "aksi", header: "Rekomendasi Aksi", render: (r) => <span className="text-slate-500">{r.rekomendasiAksi}</span> }, { key: "prioritas", header: "Prioritas", render: (r) => <AdsRoasStatusBadge label={r.prioritas} tone={PRIORITY_TONE[r.prioritas]} /> }]; return <><div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><AdsRoasChartCard title="Jenis Issue Data"><RoasDonutChart data={data.issueTypeDonut} formatValue={formatNumber} /></AdsRoasChartCard><AdsRoasChartCard title="Jumlah Issue per Tipe Data"><HorizontalValueBars data={data.issuePerType.map((i) => ({ label: i.name, value: i.value }))} formatValue={formatNumber} /></AdsRoasChartCard></div><AdsRoasChartCard title="Data Review"><TableWithoutSeeAll columns={columns} rows={data.table} rowKey={(r) => `${r.tipeData}-${r.masalah}`} /></AdsRoasChartCard></>; }
function TableWithoutSeeAll<T>({ columns, rows, rowKey }: { columns: AdsRoasTableColumn<T>[]; rows: T[]; rowKey: (row: T) => string }) { if (rows.length === 0) return <p className="rounded-2xl bg-slate-50 p-6 text-center text-xs font-semibold text-slate-400">Belum ada data untuk filter ini.</p>; return <div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b border-slate-100 text-slate-400">{columns.map((col) => <th key={col.key} className={`pb-2 pr-4 text-xs font-bold uppercase tracking-[0.02em] ${col.align === "right" ? "text-right" : ""}`}>{col.header}</th>)}</tr></thead><tbody className="divide-y divide-slate-50 font-medium text-slate-700">{rows.map((row) => <tr key={rowKey(row)}>{columns.map((col) => <td key={col.key} className={`py-3 pr-4 ${col.align === "right" ? "text-right" : ""}`}>{col.render(row)}</td>)}</tr>)}</tbody></table></div>; }
